language: node_js
node_js:
  - 10.15.0
branches:
  only:
    - master
install:
  - npm install

before-script:
  - node ./test/fixtures/server.js &
script:
  - npm run build
  - npm run cover -- --allow-chrome-as-root
after_success:
  - npm run coveralls